Adding Java Script exercise changes
YashawanthkumarH/JavaScriptExercises pull request #2
Opened 2024-03-14 06:53 UTC by YashawanthkumarH

2024-03-14 08:59 UTC, vikaskumar6172 requested changes

2024-03-14 08:59 UTC, vikaskumar6172 commented on tests/exercise.spec.js
> +        await test.step("Then: Deploy the wordpress website", async function () {
try having an assertion in the then block, preferably at the last of it.

2024-03-14 08:59 UTC, vikaskumar6172 commented on tests/exercise.spec.js
> +            await createSite.deployWordpress.visitSiteDashBoard();
see if an assertion can be added

2024-03-18 13:28 UTC, OmTrivedi01 approved these changes

2024-03-19 04:58 UTC, vikaskumar6172 approved these changes

2024-03-19 06:02 UTC, merged